// import { Geist, Geist_Mono } from "next/font/google";
// import "../globals.css";
// import Footer from "../components/Footer";
// import Navbar from "../components/Navbar";

// import { NextIntlClientProvider } from "next-intl";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "EduPortal",
//   description:
//     "Learn and practice with international exams like TIMSS, PISA, PIRLS, and TOEFL.",
// };

// export default async function RootLayout({ children, params }) {
//   const { locale } = params;

//   // ✅ define supported locales
//   const supportedLocales = ["en", "ar"];
//   const currentLocale = supportedLocales.includes(locale) ? locale : "en";

//   let messages;
//   try {
//     messages = (await import(`../messages/${currentLocale}.json`)).default;
//   } catch (error) {
//     // fallback to English if file missing
//     messages = (await import(`../messages/en.json`)).default;
//   }

//   return (
//     <html lang={currentLocale} dir={currentLocale === "ar" ? "rtl" : "ltr"}>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <NextIntlClientProvider locale={currentLocale} messages={messages}>
//           <Navbar locale={currentLocale} />
//           {children}
//           <Footer />
//         </NextIntlClientProvider>
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import { Geist, Geist_Mono } from "next/font/google";
import { Cairo } from "next/font/google"; // ✅ Arabic font

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cairo = Cairo({
  variable: "--font-arabic",
  subsets: ["arabic"],
  weight: ["400", "500", "700"], // choose weights you need
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
